#!/bin/sh

if ( test "$USER" != "root" ); then
  echo "This script must be executed as root!"
  exit 1
fi

PACKAGE=python-rfid
DIR=src

if ( ! test -d "$DIR" ); then
  echo "The directory does not exists!"
  exit 1
fi

cp -R "$DIR" "${PACKAGE}_temp/"
dpkg --build "${PACKAGE}_temp/" "${PACKAGE}.deb"
chown 1000:1000 "${PACKAGE}.deb"

rm -R "${PACKAGE}_temp/"
