.TH pyrfid 1 "June 2014" "" "PyRFID"

.SH NAME
\fBpyrfid\fP - Python library for using a 125kHz RFID reader

.SH DESCRIPTION
\fBpyrfid\fR is a Python written library for using a 125kHz RFID reader. The library was developed with the RDM6300 RFID reader which is used for reading tags with the 125kHz specification. The reader uses UART to communicate so it is possible to connect it with a USB-TTL converter.

.SH EXAMPLE
How to use the library: See file "example-read.py" in /usr/share/doc/python-rfid/examples/.

.SH AUTHOR
Philipp Meisberger <team@pm-codeworks.de> 

Please send bug reports to one of those mail addresses. Visit http://www.pm-codeworks.de for more interesting projects.
